name:   Christian Michael Schneider
street:   Thunstrasse 3
city:   CH-3114 Wichtrach
country: Switzerland
birthdate: 2 May 1978
nationality: Swiss and British nationalities
phone: +41 78 882 67 08
email: info@chrischne.io
website: www.christianschneider.ch 

photo: img/photo_cs.jpg 

markdown:   kramdown


collections:
  education:
    output: false
  employment:
    output: false
  teaching:
    output: false
  conferences:
    output: false
  exhibitions:
    output: false
  misc:
    output: false
  computer_skills:
    output: false
  languages:
    output: false
  interests:
    output: false



