name:   Christian Michael Schneider
street:   Juliastrasse 8
city:   CH-8032 Zurich
country: Switzerland
birthdate: 02.05.1978
nationality: Swiss and British nationalities
phone: +41 78 882 67 08
email: chrischne@gmail.com
website: www.christianschneider.ch 

markdown:   kramdown

collections:
  education:
    output: false
  employment:
    output: false
  teaching:
    output: false

